Improve unmigrate data check in the the preinst script
Use the return code of the rake task before proceeding
and show the output of the Rake task if this fails to
aid debugging.

diff --git a/docker/assets/wrapper b/docker/assets/wrapper
--- a/docker/assets/wrapper
+++ b/docker/assets/wrapper
@@ -49,8 +49,20 @@ function unmigrated_data_check() {
     set +e
 
     echo "Checking for unmigrated data on legacy storage"
+    found=$(MAX_DATABASE_CONNECTION_CHECKS=5 gitlab-rake gitlab:storage:legacy_attachments gitlab:storage:legacy_projects 2>&1);
 
-    found=$(MAX_DATABASE_CONNECTION_CHECKS=5 gitlab-rake gitlab:storage:legacy_attachments gitlab:storage:legacy_projects 2>/dev/null);
+    if [ $? -ne 0 ]; then
+        echo "Upgrade failed. Could not check for unmigrated data on legacy storage."
+        echo ""
+        echo $output
+        echo ""
+        echo ""
+        echo "If you would like to restart the instance without perfming this check"
+        echo "check, add the following to your docker command:"
+        echo "-e GITLAB_SKIP_UNMIGRATED_DATA_CHECK=true"
+        echo ""
+        exit 1
+    fi
 
     if ! (echo $found | grep 'Found 0 attachments' && echo $found | grep 'Found 0 projects') > /dev/null 2>&1; then
         echo
