Remove some unneeded pretifying.

diff --git a/files/gitlab-scripts/symlink_ctl_cmds b/files/gitlab-scripts/symlink_ctl_cmds
--- a/files/gitlab-scripts/symlink_ctl_cmds
+++ b/files/gitlab-scripts/symlink_ctl_cmds
@@ -18,7 +18,7 @@ symlink_command="ln -sf ${usr_bin_symlinks} /usr/bin/"
 
 error_exit()
 {
-  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  echo "${1:-"Unknown Error"}" 1>&2
   exit 1
 }
 
